[project]
name = "daily-bits"
version = "0.1.0"
description = "Learn something new every day!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.16.0",
    "python-dotenv>=1.2.2",
    "wikipedia-api>=0.15.0",
]

[project.scripts]
daily-bits = "daily_bits.main:main"

[tool.uv]
package = true